# Default values for keycloak.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
# For a complete list of parameters that can be set from this file refer to:
# https://github.com/codecentric/helm-charts/blob/keycloak-18.4.4/charts/keycloak/values.yaml
args:
  - -Dkeycloak.profile.feature.docker=enabled
extraEnv: |
  - name: KEYCLOAK_LOGLEVEL
    value: DEBUG
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KEYCLOAK_USER
    value: admin
  - name: KEYCLOAK_PASSWORD
    value: password
ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "<this value is overriden by terraform/helm_releases.tf>"
    kubernetes.io/ingress.class: "nginx"
  rules:
    - host: "<this value is overriden by terraform/helm_releases.tf>"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - "<this value is overriden by terraform/helm_releases.tf>"
      secretName: "<this value is overriden by terraform/helm_releases.tf>"
postgresql:
  enabled: true
  postgresqlPassword: "<this value is overriden by terraform/helm_releases.tf>"
