---
# Default values for superset.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
# For a complete list of parameters that can be set from this file refer to:
# https://github.com/apache/superset/blob/superset-helm-chart-0.11.2/helm/superset/values.yaml
bootstrapScript: |
  #!/bin/bash
  if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi
  pip3 install authlib==1.3.0
extraSecretEnv:
  SUPERSET_SECRET_KEY: "<this value is overriden by terraform/helm_releases.tf>"
  GITHUB_AUTH_APP_CLIENT_ID: "<this value is overriden by terraform/helm_releases.tf>"
  GITHUB_AUTH_APP_CLIENT_SECRET: "<this value is overriden by terraform/helm_releases.tf>"
configOverrides:
  enable_oauth: |
    import os
    import json
    import logging
    from flask_appbuilder.security.manager import (AUTH_DB, AUTH_OAUTH)
    from superset.security import SupersetSecurityManager

    ENABLE_PROXY_FIX = True
    AUTH_TYPE = AUTH_OAUTH
    AUTH_ROLES_SYNC_AT_LOGIN = True   # Sync roles on every login
    AUTH_USER_REGISTRATION = True     # Allow users to self register
    AUTH_USER_REGISTRATION_ROLE = "Public"  # Default role for self-registered users
    AUTH_ROLES_MAPPING = {
        "admin": ["Admin"],
        "engineer": ["Alpha", "sql_lab"],
        "scientist": ["Gamma", "sql_lab"],
        "analyst": ["Gamma", "sql_lab"],
        "viewer": ["Gamma"]
    }
    RBAC = json.loads(os.environ.get("RBAC"))
    OAUTH_PROVIDERS = [
        {
            "name": "github",
            "icon": "fa-github",
            "token_key": "access_token",
            "remote_app": {
                "client_id": os.environ.get("GITHUB_AUTH_APP_CLIENT_ID"),
                "client_secret": os.environ.get("GITHUB_AUTH_APP_CLIENT_SECRET"),
                "api_base_url": "https://api.github.com",
                "client_kwargs": {"scope": "read:user, read:org"},
                "access_token_url":
                  "https://github.com/login/oauth/access_token",
                "authorize_url": "https://github.com/login/oauth/authorize",
                "request_token_url": None,
            },
        },
    ]


    class GithubAuthoriser(SupersetSecurityManager):
        def oauth_user_info(self, provider, resp):
            remote_app = self.appbuilder.sm.oauth_remotes[provider]
            me = remote_app.get("user")
            user_data = me.json()
            username = user_data.get("login")
            try:
              role_keys = [RBAC[username]["platform_role"]]
            except KeyError as e:
              logging.error(f"Permission denied to user {username}")
              raise Exception(e)
            return {
              "username": user_data.get("login"),
              "role_keys": role_keys
            }


    CUSTOM_SECURITY_MANAGER = GithubAuthoriser
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: "<this value is overriden by terraform/helm_releases.tf>"
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - "<this value is overriden by terraform/helm_releases.tf>"
  tls:
    - secretName: "<this value is overriden by terraform/helm_releases.tf>"
      hosts:
        - "<this value is overriden by terraform/helm_releases.tf>"
