---
# Default values for jupyterhub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
# For a complete list of parameters that can be set from this file refer to:
# https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/3.2.1/jupyterhub/values.yaml
hub:
  config:
    JupyterHub:
      authenticator_class: github
    OAuthenticator:
      oauth_callback_url: "<this value is overriden by terraform/helm_releases.tf>"
      client_id: "<this value is overriden by terraform/helm_releases.tf>"
      client_secret: "<this value is overriden by terraform/helm_releases.tf>"
    GitHubOAuthenticator:
      scope:
        - "read:user"
        - "read:org"
proxy:
  service:
    type: ClusterIP
singleuser:
  networkPolicy:
    egress:
      - to:
          - podSelector:
              matchLabels:
                app.kubernetes.io/component: clickhouse
                app.kubernetes.io/instance: clickhouse
                app.kubernetes.io/name: clickhouse
ingress:
  enabled: true
  annotations:
    cert-manager.io/issuer: "<this value is overriden by terraform/helm_releases.tf>"
  ingressClassName: nginx
  tls:
    - secretName: "<this value is overriden by terraform/helm_releases.tf>"
