---
name: Lint

on: push

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter/slim@v5.7.2  # x-release-please-version
        env:
          DEFAULT_BRANCH: main
          VALIDATE_TERRAFORM_TFLINT: true
          VALIDATE_YAML: true
